// Code generated by internal/codegen. DO NOT EDIT.

package smartcharging

import (
	"reflect"

	"gopkg.in/go-playground/validator.v9"

	"github.com/enesismail/ocpp-go/ocpp2.0.1/types"
)

// -------------------- Set Charging Profile (CSMS -> CS) --------------------

const SetChargingProfileFeatureName = "SetChargingProfile"

type ChargingProfileStatusType string

const (
	ChargingProfileStatusTypeAccepted ChargingProfileStatusType = "Accepted"
	ChargingProfileStatusTypeRejected ChargingProfileStatusType = "Rejected"
)

func isValidChargingProfileStatusType(fl validator.FieldLevel) bool {
	chargingProfileStatus := ChargingProfileStatusType(fl.Field().String())
	switch chargingProfileStatus {
	case ChargingProfileStatusTypeAccepted, ChargingProfileStatusTypeRejected:
		return true
	default:
		return false
	}
}

type SetChargingProfileRequest struct {
	CustomData      *types.CustomData     `json:"customData,omitempty" validate:"omitempty"`
	EVSEID          int                   `json:"evseId" validate:"required"`
	ChargingProfile types.ChargingProfile `json:"chargingProfile" validate:"required"`
}

type SetChargingProfileResponse struct {
	CustomData *types.CustomData         `json:"customData,omitempty" validate:"omitempty"`
	Status     ChargingProfileStatusType `json:"status" validate:"required,chargingProfileStatusType201"`
	StatusInfo *types.StatusInfo         `json:"statusInfo,omitempty" validate:"omitempty"`
}

type SetChargingProfileFeature struct{}

func (f SetChargingProfileFeature) GetFeatureName() string {
	return SetChargingProfileFeatureName
}

func (f SetChargingProfileFeature) GetRequestType() reflect.Type {
	return reflect.TypeOf(SetChargingProfileRequest{})
}

func (f SetChargingProfileFeature) GetResponseType() reflect.Type {
	return reflect.TypeOf(SetChargingProfileResponse{})
}

func (r SetChargingProfileRequest) GetFeatureName() string {
	return SetChargingProfileFeatureName
}

func (c SetChargingProfileResponse) GetFeatureName() string {
	return SetChargingProfileFeatureName
}

func NewSetChargingProfileRequest(evseid int, chargingProfile types.ChargingProfile) *SetChargingProfileRequest {
	return &SetChargingProfileRequest{EVSEID: evseid, ChargingProfile: chargingProfile}
}

func NewSetChargingProfileResponse(status ChargingProfileStatusType) *SetChargingProfileResponse {
	return &SetChargingProfileResponse{Status: status}
}

func init() {
	_ = types.Validate.RegisterValidation("chargingProfileStatusType201", isValidChargingProfileStatusType)
}
