// Code generated by internal/codegen. DO NOT EDIT.

package types

import (
	"gopkg.in/go-playground/validator.v9"
)

type AdditionalInfo struct {
	CustomData        *CustomData `json:"customData,omitempty" validate:"omitempty"`
	AdditionalIDToken string      `json:"additionalIdToken" validate:"required,max=36"`
	Type              string      `json:"type" validate:"required,max=50"`
}

func NewAdditionalInfo(additionalIDToken string, type_ string) AdditionalInfo {
	return AdditionalInfo{AdditionalIDToken: additionalIDToken, Type: type_}
}

type AttributeType string

const (
	AttributeTypeActual AttributeType = "Actual"
	AttributeTypeTarget AttributeType = "Target"
	AttributeTypeMinSet AttributeType = "MinSet"
	AttributeTypeMaxSet AttributeType = "MaxSet"
)

func isValidAttributeType(fl validator.FieldLevel) bool {
	attribute := AttributeType(fl.Field().String())
	switch attribute {
	case AttributeTypeActual, AttributeTypeTarget, AttributeTypeMinSet, AttributeTypeMaxSet:
		return true
	default:
		return false
	}
}

type AuthorizationStatusType string

const (
	AuthorizationStatusTypeAccepted           AuthorizationStatusType = "Accepted"
	AuthorizationStatusTypeBlocked            AuthorizationStatusType = "Blocked"
	AuthorizationStatusTypeConcurrentTx       AuthorizationStatusType = "ConcurrentTx"
	AuthorizationStatusTypeExpired            AuthorizationStatusType = "Expired"
	AuthorizationStatusTypeInvalid            AuthorizationStatusType = "Invalid"
	AuthorizationStatusTypeNoCredit           AuthorizationStatusType = "NoCredit"
	AuthorizationStatusTypeNotAllowedTypeEVSE AuthorizationStatusType = "NotAllowedTypeEVSE"
	AuthorizationStatusTypeNotAtThisLocation  AuthorizationStatusType = "NotAtThisLocation"
	AuthorizationStatusTypeNotAtThisTime      AuthorizationStatusType = "NotAtThisTime"
	AuthorizationStatusTypeUnknown            AuthorizationStatusType = "Unknown"
)

func isValidAuthorizationStatusType(fl validator.FieldLevel) bool {
	authorizationStatus := AuthorizationStatusType(fl.Field().String())
	switch authorizationStatus {
	case AuthorizationStatusTypeAccepted, AuthorizationStatusTypeBlocked, AuthorizationStatusTypeConcurrentTx, AuthorizationStatusTypeExpired, AuthorizationStatusTypeInvalid, AuthorizationStatusTypeNoCredit, AuthorizationStatusTypeNotAllowedTypeEVSE, AuthorizationStatusTypeNotAtThisLocation, AuthorizationStatusTypeNotAtThisTime, AuthorizationStatusTypeUnknown:
		return true
	default:
		return false
	}
}

type CertificateHashData struct {
	CustomData     *CustomData       `json:"customData,omitempty" validate:"omitempty"`
	HashAlgorithm  HashAlgorithmType `json:"hashAlgorithm" validate:"required,hashAlgorithmType201"`
	IssuerNameHash string            `json:"issuerNameHash" validate:"required,max=128"`
	IssuerKeyHash  string            `json:"issuerKeyHash" validate:"required,max=128"`
	SerialNumber   string            `json:"serialNumber" validate:"required,max=40"`
}

func NewCertificateHashData(hashAlgorithm HashAlgorithmType, issuerNameHash string, issuerKeyHash string, serialNumber string) *CertificateHashData {
	return &CertificateHashData{HashAlgorithm: hashAlgorithm, IssuerNameHash: issuerNameHash, IssuerKeyHash: issuerKeyHash, SerialNumber: serialNumber}
}

type CertificateSigningUseType string

const (
	CertificateSigningUseTypeChargingStationCertificate CertificateSigningUseType = "ChargingStationCertificate"
	CertificateSigningUseTypeV2GCertificate             CertificateSigningUseType = "V2GCertificate"
)

func isValidCertificateSigningUseType(fl validator.FieldLevel) bool {
	certificateSigningUse := CertificateSigningUseType(fl.Field().String())
	switch certificateSigningUse {
	case CertificateSigningUseTypeChargingStationCertificate, CertificateSigningUseTypeV2GCertificate:
		return true
	default:
		return false
	}
}

type ChargingLimitSourceType string

const (
	ChargingLimitSourceTypeEMS   ChargingLimitSourceType = "EMS"
	ChargingLimitSourceTypeOther ChargingLimitSourceType = "Other"
	ChargingLimitSourceTypeSO    ChargingLimitSourceType = "SO"
	ChargingLimitSourceTypeCSO   ChargingLimitSourceType = "CSO"
)

func isValidChargingLimitSourceType(fl validator.FieldLevel) bool {
	chargingLimitSource := ChargingLimitSourceType(fl.Field().String())
	switch chargingLimitSource {
	case ChargingLimitSourceTypeEMS, ChargingLimitSourceTypeOther, ChargingLimitSourceTypeSO, ChargingLimitSourceTypeCSO:
		return true
	default:
		return false
	}
}

type ChargingProfile struct {
	CustomData             *CustomData                `json:"customData,omitempty" validate:"omitempty"`
	ID                     int                        `json:"id" validate:"required"`
	StackLevel             int                        `json:"stackLevel" validate:"required"`
	ChargingProfilePurpose ChargingProfilePurposeType `json:"chargingProfilePurpose" validate:"required,chargingProfilePurposeType201"`
	ChargingProfileKind    ChargingProfileKindType    `json:"chargingProfileKind" validate:"required,chargingProfileKindType201"`
	RecurrencyKind         RecurrencyKindType         `json:"recurrencyKind,omitempty" validate:"omitempty,recurrencyKindType201"`
	ValidFrom              *DateTime                  `json:"validFrom,omitempty" validate:"omitempty"`
	ValidTo                *DateTime                  `json:"validTo,omitempty" validate:"omitempty"`
	ChargingSchedule       []ChargingSchedule         `json:"chargingSchedule" validate:"required,min=1,max=3,dive"`
	TransactionID          string                     `json:"transactionId,omitempty" validate:"omitempty,max=36"`
}

func NewChargingProfile(id int, stackLevel int, chargingProfilePurpose ChargingProfilePurposeType, chargingProfileKind ChargingProfileKindType, chargingSchedule []ChargingSchedule) *ChargingProfile {
	return &ChargingProfile{ID: id, StackLevel: stackLevel, ChargingProfilePurpose: chargingProfilePurpose, ChargingProfileKind: chargingProfileKind, ChargingSchedule: chargingSchedule}
}

type ChargingProfileKindType string

const (
	ChargingProfileKindTypeAbsolute  ChargingProfileKindType = "Absolute"
	ChargingProfileKindTypeRecurring ChargingProfileKindType = "Recurring"
	ChargingProfileKindTypeRelative  ChargingProfileKindType = "Relative"
)

func isValidChargingProfileKindType(fl validator.FieldLevel) bool {
	chargingProfileKind := ChargingProfileKindType(fl.Field().String())
	switch chargingProfileKind {
	case ChargingProfileKindTypeAbsolute, ChargingProfileKindTypeRecurring, ChargingProfileKindTypeRelative:
		return true
	default:
		return false
	}
}

type ChargingProfilePurposeType string

const (
	ChargingProfilePurposeTypeChargingStationExternalConstraints ChargingProfilePurposeType = "ChargingStationExternalConstraints"
	ChargingProfilePurposeTypeChargingStationMaxProfile          ChargingProfilePurposeType = "ChargingStationMaxProfile"
	ChargingProfilePurposeTypeTxDefaultProfile                   ChargingProfilePurposeType = "TxDefaultProfile"
	ChargingProfilePurposeTypeTxProfile                          ChargingProfilePurposeType = "TxProfile"
)

func isValidChargingProfilePurposeType(fl validator.FieldLevel) bool {
	chargingProfilePurpose := ChargingProfilePurposeType(fl.Field().String())
	switch chargingProfilePurpose {
	case ChargingProfilePurposeTypeChargingStationExternalConstraints, ChargingProfilePurposeTypeChargingStationMaxProfile, ChargingProfilePurposeTypeTxDefaultProfile, ChargingProfilePurposeTypeTxProfile:
		return true
	default:
		return false
	}
}

type ChargingRateUnitType string

const (
	ChargingRateUnitTypeW ChargingRateUnitType = "W"
	ChargingRateUnitTypeA ChargingRateUnitType = "A"
)

func isValidChargingRateUnitType(fl validator.FieldLevel) bool {
	chargingRateUnit := ChargingRateUnitType(fl.Field().String())
	switch chargingRateUnit {
	case ChargingRateUnitTypeW, ChargingRateUnitTypeA:
		return true
	default:
		return false
	}
}

type ChargingSchedule struct {
	CustomData             *CustomData              `json:"customData,omitempty" validate:"omitempty"`
	ID                     int                      `json:"id" validate:"required"`
	StartSchedule          *DateTime                `json:"startSchedule,omitempty" validate:"omitempty"`
	Duration               *int                     `json:"duration,omitempty" validate:"omitempty"`
	ChargingRateUnit       ChargingRateUnitType     `json:"chargingRateUnit" validate:"required,chargingRateUnitType201"`
	ChargingSchedulePeriod []ChargingSchedulePeriod `json:"chargingSchedulePeriod" validate:"required,min=1,max=1024,dive"`
	MinChargingRate        *float64                 `json:"minChargingRate,omitempty" validate:"omitempty"`
	SalesTariff            *SalesTariff             `json:"salesTariff,omitempty" validate:"omitempty"`
}

func NewChargingSchedule(id int, chargingRateUnit ChargingRateUnitType, chargingSchedulePeriod []ChargingSchedulePeriod) ChargingSchedule {
	return ChargingSchedule{ID: id, ChargingRateUnit: chargingRateUnit, ChargingSchedulePeriod: chargingSchedulePeriod}
}

type ChargingSchedulePeriod struct {
	CustomData   *CustomData `json:"customData,omitempty" validate:"omitempty"`
	StartPeriod  int         `json:"startPeriod" validate:"required"`
	Limit        float64     `json:"limit" validate:"required"`
	NumberPhases *int        `json:"numberPhases,omitempty" validate:"omitempty"`
	PhaseToUse   *int        `json:"phaseToUse,omitempty" validate:"omitempty"`
}

func NewChargingSchedulePeriod(startPeriod int, limit float64) ChargingSchedulePeriod {
	return ChargingSchedulePeriod{StartPeriod: startPeriod, Limit: limit}
}

type Component struct {
	CustomData *CustomData `json:"customData,omitempty" validate:"omitempty"`
	EVSE       *EVSE       `json:"evse,omitempty" validate:"omitempty"`
	Name       string      `json:"name" validate:"required,max=50"`
	Instance   string      `json:"instance,omitempty" validate:"omitempty,max=50"`
}

func NewComponent(name string) *Component {
	return &Component{Name: name}
}

type ComponentVariable struct {
	CustomData *CustomData `json:"customData,omitempty" validate:"omitempty"`
	Component  Component   `json:"component" validate:"required"`
	Variable   *Variable   `json:"variable,omitempty" validate:"omitempty"`
}

func NewComponentVariable(component Component) ComponentVariable {
	return ComponentVariable{Component: component}
}

type ConsumptionCost struct {
	CustomData *CustomData `json:"customData,omitempty" validate:"omitempty"`
	StartValue float64     `json:"startValue" validate:"required"`
	Cost       []Cost      `json:"cost" validate:"required,min=1,max=3,dive"`
}

func NewConsumptionCost(startValue float64, cost []Cost) ConsumptionCost {
	return ConsumptionCost{StartValue: startValue, Cost: cost}
}

type Cost struct {
	CustomData       *CustomData  `json:"customData,omitempty" validate:"omitempty"`
	CostKind         CostKindType `json:"costKind" validate:"required,costKindType201"`
	Amount           int          `json:"amount" validate:"required"`
	AmountMultiplier *int         `json:"amountMultiplier,omitempty" validate:"omitempty"`
}

func NewCost(costKind CostKindType, amount int) Cost {
	return Cost{CostKind: costKind, Amount: amount}
}

type CostKindType string

const (
	CostKindTypeCarbonDioxideEmission         CostKindType = "CarbonDioxideEmission"
	CostKindTypeRelativePricePercentage       CostKindType = "RelativePricePercentage"
	CostKindTypeRenewableGenerationPercentage CostKindType = "RenewableGenerationPercentage"
)

func isValidCostKindType(fl validator.FieldLevel) bool {
	costKind := CostKindType(fl.Field().String())
	switch costKind {
	case CostKindTypeCarbonDioxideEmission, CostKindTypeRelativePricePercentage, CostKindTypeRenewableGenerationPercentage:
		return true
	default:
		return false
	}
}

type EVSE struct {
	CustomData  *CustomData `json:"customData,omitempty" validate:"omitempty"`
	ID          int         `json:"id" validate:"required"`
	ConnectorID *int        `json:"connectorId,omitempty" validate:"omitempty"`
}

func NewEVSE(id int) *EVSE {
	return &EVSE{ID: id}
}

type GenericDeviceModelStatusType string

const (
	GenericDeviceModelStatusTypeAccepted       GenericDeviceModelStatusType = "Accepted"
	GenericDeviceModelStatusTypeRejected       GenericDeviceModelStatusType = "Rejected"
	GenericDeviceModelStatusTypeNotSupported   GenericDeviceModelStatusType = "NotSupported"
	GenericDeviceModelStatusTypeEmptyResultSet GenericDeviceModelStatusType = "EmptyResultSet"
)

func isValidGenericDeviceModelStatusType(fl validator.FieldLevel) bool {
	genericDeviceModelStatus := GenericDeviceModelStatusType(fl.Field().String())
	switch genericDeviceModelStatus {
	case GenericDeviceModelStatusTypeAccepted, GenericDeviceModelStatusTypeRejected, GenericDeviceModelStatusTypeNotSupported, GenericDeviceModelStatusTypeEmptyResultSet:
		return true
	default:
		return false
	}
}

type GenericStatusType string

const (
	GenericStatusTypeAccepted GenericStatusType = "Accepted"
	GenericStatusTypeRejected GenericStatusType = "Rejected"
)

func isValidGenericStatusType(fl validator.FieldLevel) bool {
	genericStatus := GenericStatusType(fl.Field().String())
	switch genericStatus {
	case GenericStatusTypeAccepted, GenericStatusTypeRejected:
		return true
	default:
		return false
	}
}

type HashAlgorithmType string

const (
	HashAlgorithmTypeSHA256 HashAlgorithmType = "SHA256"
	HashAlgorithmTypeSHA384 HashAlgorithmType = "SHA384"
	HashAlgorithmTypeSHA512 HashAlgorithmType = "SHA512"
)

func isValidHashAlgorithmType(fl validator.FieldLevel) bool {
	hashAlgorithm := HashAlgorithmType(fl.Field().String())
	switch hashAlgorithm {
	case HashAlgorithmTypeSHA256, HashAlgorithmTypeSHA384, HashAlgorithmTypeSHA512:
		return true
	default:
		return false
	}
}

type IDToken struct {
	CustomData     *CustomData      `json:"customData,omitempty" validate:"omitempty"`
	AdditionalInfo []AdditionalInfo `json:"additionalInfo,omitempty" validate:"omitempty,min=1,dive"`
	IDToken        string           `json:"idToken" validate:"required,max=36"`
	Type           IDTokenType      `json:"type" validate:"required,idTokenType201"`
}

func NewIDToken(idToken string, type_ IDTokenType) *IDToken {
	return &IDToken{IDToken: idToken, Type: type_}
}

type IDTokenInfo struct {
	CustomData          *CustomData             `json:"customData,omitempty" validate:"omitempty"`
	Status              AuthorizationStatusType `json:"status" validate:"required,authorizationStatusType201"`
	CacheExpiryDateTime *DateTime               `json:"cacheExpiryDateTime,omitempty" validate:"omitempty"`
	ChargingPriority    *int                    `json:"chargingPriority,omitempty" validate:"omitempty"`
	Language1           string                  `json:"language1,omitempty" validate:"omitempty,max=8"`
	EVSEID              []int                   `json:"evseId,omitempty" validate:"omitempty,min=1"`
	GroupIDToken        *IDToken                `json:"groupIdToken,omitempty" validate:"omitempty"`
	Language2           string                  `json:"language2,omitempty" validate:"omitempty,max=8"`
	PersonalMessage     *MessageContent         `json:"personalMessage,omitempty" validate:"omitempty"`
}

func NewIDTokenInfo(status AuthorizationStatusType) *IDTokenInfo {
	return &IDTokenInfo{Status: status}
}

type IDTokenType string

const (
	IDTokenTypeCentral         IDTokenType = "Central"
	IDTokenTypeEMAID           IDTokenType = "eMAID"
	IDTokenTypeISO14443        IDTokenType = "ISO14443"
	IDTokenTypeISO15693        IDTokenType = "ISO15693"
	IDTokenTypeKeyCode         IDTokenType = "KeyCode"
	IDTokenTypeLocal           IDTokenType = "Local"
	IDTokenTypeMacAddress      IDTokenType = "MacAddress"
	IDTokenTypeNoAuthorization IDTokenType = "NoAuthorization"
)

func isValidIDTokenType(fl validator.FieldLevel) bool {
	idToken := IDTokenType(fl.Field().String())
	switch idToken {
	case IDTokenTypeCentral, IDTokenTypeEMAID, IDTokenTypeISO14443, IDTokenTypeISO15693, IDTokenTypeKeyCode, IDTokenTypeLocal, IDTokenTypeMacAddress, IDTokenTypeNoAuthorization:
		return true
	default:
		return false
	}
}

type LocationType string

const (
	LocationTypeBody   LocationType = "Body"
	LocationTypeCable  LocationType = "Cable"
	LocationTypeEV     LocationType = "EV"
	LocationTypeInlet  LocationType = "Inlet"
	LocationTypeOutlet LocationType = "Outlet"
)

func isValidLocationType(fl validator.FieldLevel) bool {
	location := LocationType(fl.Field().String())
	switch location {
	case LocationTypeBody, LocationTypeCable, LocationTypeEV, LocationTypeInlet, LocationTypeOutlet:
		return true
	default:
		return false
	}
}

type MeasurandType string

const (
	MeasurandTypeCurrentExport                MeasurandType = "Current.Export"
	MeasurandTypeCurrentImport                MeasurandType = "Current.Import"
	MeasurandTypeCurrentOffered               MeasurandType = "Current.Offered"
	MeasurandTypeEnergyActiveExportRegister   MeasurandType = "Energy.Active.Export.Register"
	MeasurandTypeEnergyActiveImportRegister   MeasurandType = "Energy.Active.Import.Register"
	MeasurandTypeEnergyReactiveExportRegister MeasurandType = "Energy.Reactive.Export.Register"
	MeasurandTypeEnergyReactiveImportRegister MeasurandType = "Energy.Reactive.Import.Register"
	MeasurandTypeEnergyActiveExportInterval   MeasurandType = "Energy.Active.Export.Interval"
	MeasurandTypeEnergyActiveImportInterval   MeasurandType = "Energy.Active.Import.Interval"
	MeasurandTypeEnergyActiveNet              MeasurandType = "Energy.Active.Net"
	MeasurandTypeEnergyReactiveExportInterval MeasurandType = "Energy.Reactive.Export.Interval"
	MeasurandTypeEnergyReactiveImportInterval MeasurandType = "Energy.Reactive.Import.Interval"
	MeasurandTypeEnergyReactiveNet            MeasurandType = "Energy.Reactive.Net"
	MeasurandTypeEnergyApparentNet            MeasurandType = "Energy.Apparent.Net"
	MeasurandTypeEnergyApparentImport         MeasurandType = "Energy.Apparent.Import"
	MeasurandTypeEnergyApparentExport         MeasurandType = "Energy.Apparent.Export"
	MeasurandTypeFrequency                    MeasurandType = "Frequency"
	MeasurandTypePowerActiveExport            MeasurandType = "Power.Active.Export"
	MeasurandTypePowerActiveImport            MeasurandType = "Power.Active.Import"
	MeasurandTypePowerFactor                  MeasurandType = "Power.Factor"
	MeasurandTypePowerOffered                 MeasurandType = "Power.Offered"
	MeasurandTypePowerReactiveExport          MeasurandType = "Power.Reactive.Export"
	MeasurandTypePowerReactiveImport          MeasurandType = "Power.Reactive.Import"
	MeasurandTypeSOC                          MeasurandType = "SoC"
	MeasurandTypeVoltage                      MeasurandType = "Voltage"
)

func isValidMeasurandType(fl validator.FieldLevel) bool {
	measurand := MeasurandType(fl.Field().String())
	switch measurand {
	case MeasurandTypeCurrentExport, MeasurandTypeCurrentImport, MeasurandTypeCurrentOffered, MeasurandTypeEnergyActiveExportRegister, MeasurandTypeEnergyActiveImportRegister, MeasurandTypeEnergyReactiveExportRegister, MeasurandTypeEnergyReactiveImportRegister, MeasurandTypeEnergyActiveExportInterval, MeasurandTypeEnergyActiveImportInterval, MeasurandTypeEnergyActiveNet, MeasurandTypeEnergyReactiveExportInterval, MeasurandTypeEnergyReactiveImportInterval, MeasurandTypeEnergyReactiveNet, MeasurandTypeEnergyApparentNet, MeasurandTypeEnergyApparentImport, MeasurandTypeEnergyApparentExport, MeasurandTypeFrequency, MeasurandTypePowerActiveExport, MeasurandTypePowerActiveImport, MeasurandTypePowerFactor, MeasurandTypePowerOffered, MeasurandTypePowerReactiveExport, MeasurandTypePowerReactiveImport, MeasurandTypeSOC, MeasurandTypeVoltage:
		return true
	default:
		return false
	}
}

type MessageContent struct {
	CustomData *CustomData       `json:"customData,omitempty" validate:"omitempty"`
	Format     MessageFormatType `json:"format" validate:"required,messageFormatType201"`
	Language   string            `json:"language,omitempty" validate:"omitempty,max=8"`
	Content    string            `json:"content" validate:"required,max=512"`
}

func NewMessageContent(format MessageFormatType, content string) *MessageContent {
	return &MessageContent{Format: format, Content: content}
}

type MessageFormatType string

const (
	MessageFormatTypeASCII MessageFormatType = "ASCII"
	MessageFormatTypeHTML  MessageFormatType = "HTML"
	MessageFormatTypeURI   MessageFormatType = "URI"
	MessageFormatTypeUTF8  MessageFormatType = "UTF8"
)

func isValidMessageFormatType(fl validator.FieldLevel) bool {
	messageFormat := MessageFormatType(fl.Field().String())
	switch messageFormat {
	case MessageFormatTypeASCII, MessageFormatTypeHTML, MessageFormatTypeURI, MessageFormatTypeUTF8:
		return true
	default:
		return false
	}
}

type MessageInfo struct {
	CustomData    *CustomData         `json:"customData,omitempty" validate:"omitempty"`
	Display       *Component          `json:"display,omitempty" validate:"omitempty"`
	ID            int                 `json:"id" validate:"required"`
	Priority      MessagePriorityType `json:"priority" validate:"required,messagePriorityType201"`
	State         MessageStateType    `json:"state,omitempty" validate:"omitempty,messageStateType201"`
	StartDateTime *DateTime           `json:"startDateTime,omitempty" validate:"omitempty"`
	EndDateTime   *DateTime           `json:"endDateTime,omitempty" validate:"omitempty"`
	TransactionID string              `json:"transactionId,omitempty" validate:"omitempty,max=36"`
	Message       MessageContent      `json:"message" validate:"required"`
}

func NewMessageInfo(id int, priority MessagePriorityType, message MessageContent) MessageInfo {
	return MessageInfo{ID: id, Priority: priority, Message: message}
}

type MessagePriorityType string

const (
	MessagePriorityTypeAlwaysFront MessagePriorityType = "AlwaysFront"
	MessagePriorityTypeInFront     MessagePriorityType = "InFront"
	MessagePriorityTypeNormalCycle MessagePriorityType = "NormalCycle"
)

func isValidMessagePriorityType(fl validator.FieldLevel) bool {
	messagePriority := MessagePriorityType(fl.Field().String())
	switch messagePriority {
	case MessagePriorityTypeAlwaysFront, MessagePriorityTypeInFront, MessagePriorityTypeNormalCycle:
		return true
	default:
		return false
	}
}

type MessageStateType string

const (
	MessageStateTypeCharging    MessageStateType = "Charging"
	MessageStateTypeFaulted     MessageStateType = "Faulted"
	MessageStateTypeIdle        MessageStateType = "Idle"
	MessageStateTypeUnavailable MessageStateType = "Unavailable"
)

func isValidMessageStateType(fl validator.FieldLevel) bool {
	messageState := MessageStateType(fl.Field().String())
	switch messageState {
	case MessageStateTypeCharging, MessageStateTypeFaulted, MessageStateTypeIdle, MessageStateTypeUnavailable:
		return true
	default:
		return false
	}
}

type MeterValue struct {
	CustomData   *CustomData    `json:"customData,omitempty" validate:"omitempty"`
	SampledValue []SampledValue `json:"sampledValue" validate:"required,min=1,dive"`
	Timestamp    *DateTime      `json:"timestamp" validate:"required"`
}

func NewMeterValue(sampledValue []SampledValue, timestamp *DateTime) MeterValue {
	return MeterValue{SampledValue: sampledValue, Timestamp: timestamp}
}

type MonitorType string

const (
	MonitorTypeUpperThreshold       MonitorType = "UpperThreshold"
	MonitorTypeLowerThreshold       MonitorType = "LowerThreshold"
	MonitorTypeDelta                MonitorType = "Delta"
	MonitorTypePeriodic             MonitorType = "Periodic"
	MonitorTypePeriodicClockAligned MonitorType = "PeriodicClockAligned"
)

func isValidMonitorType(fl validator.FieldLevel) bool {
	monitor := MonitorType(fl.Field().String())
	switch monitor {
	case MonitorTypeUpperThreshold, MonitorTypeLowerThreshold, MonitorTypeDelta, MonitorTypePeriodic, MonitorTypePeriodicClockAligned:
		return true
	default:
		return false
	}
}

type OCSPRequestData struct {
	CustomData     *CustomData       `json:"customData,omitempty" validate:"omitempty"`
	HashAlgorithm  HashAlgorithmType `json:"hashAlgorithm" validate:"required,hashAlgorithmType201"`
	IssuerNameHash string            `json:"issuerNameHash" validate:"required,max=128"`
	IssuerKeyHash  string            `json:"issuerKeyHash" validate:"required,max=128"`
	SerialNumber   string            `json:"serialNumber" validate:"required,max=40"`
	ResponderURL   string            `json:"responderURL" validate:"required,max=512"`
}

func NewOCSPRequestData(hashAlgorithm HashAlgorithmType, issuerNameHash string, issuerKeyHash string, serialNumber string, responderURL string) OCSPRequestData {
	return OCSPRequestData{HashAlgorithm: hashAlgorithm, IssuerNameHash: issuerNameHash, IssuerKeyHash: issuerKeyHash, SerialNumber: serialNumber, ResponderURL: responderURL}
}

type PhaseType string

const (
	PhaseTypeL1   PhaseType = "L1"
	PhaseTypeL2   PhaseType = "L2"
	PhaseTypeL3   PhaseType = "L3"
	PhaseTypeN    PhaseType = "N"
	PhaseTypeL1N  PhaseType = "L1-N"
	PhaseTypeL2N  PhaseType = "L2-N"
	PhaseTypeL3N  PhaseType = "L3-N"
	PhaseTypeL1L2 PhaseType = "L1-L2"
	PhaseTypeL2L3 PhaseType = "L2-L3"
	PhaseTypeL3L1 PhaseType = "L3-L1"
)

func isValidPhaseType(fl validator.FieldLevel) bool {
	phase := PhaseType(fl.Field().String())
	switch phase {
	case PhaseTypeL1, PhaseTypeL2, PhaseTypeL3, PhaseTypeN, PhaseTypeL1N, PhaseTypeL2N, PhaseTypeL3N, PhaseTypeL1L2, PhaseTypeL2L3, PhaseTypeL3L1:
		return true
	default:
		return false
	}
}

type ReadingContextType string

const (
	ReadingContextTypeInterruptionBegin ReadingContextType = "Interruption.Begin"
	ReadingContextTypeInterruptionEnd   ReadingContextType = "Interruption.End"
	ReadingContextTypeOther             ReadingContextType = "Other"
	ReadingContextTypeSampleClock       ReadingContextType = "Sample.Clock"
	ReadingContextTypeSamplePeriodic    ReadingContextType = "Sample.Periodic"
	ReadingContextTypeTransactionBegin  ReadingContextType = "Transaction.Begin"
	ReadingContextTypeTransactionEnd    ReadingContextType = "Transaction.End"
	ReadingContextTypeTrigger           ReadingContextType = "Trigger"
)

func isValidReadingContextType(fl validator.FieldLevel) bool {
	readingContext := ReadingContextType(fl.Field().String())
	switch readingContext {
	case ReadingContextTypeInterruptionBegin, ReadingContextTypeInterruptionEnd, ReadingContextTypeOther, ReadingContextTypeSampleClock, ReadingContextTypeSamplePeriodic, ReadingContextTypeTransactionBegin, ReadingContextTypeTransactionEnd, ReadingContextTypeTrigger:
		return true
	default:
		return false
	}
}

type RecurrencyKindType string

const (
	RecurrencyKindTypeDaily  RecurrencyKindType = "Daily"
	RecurrencyKindTypeWeekly RecurrencyKindType = "Weekly"
)

func isValidRecurrencyKindType(fl validator.FieldLevel) bool {
	recurrencyKind := RecurrencyKindType(fl.Field().String())
	switch recurrencyKind {
	case RecurrencyKindTypeDaily, RecurrencyKindTypeWeekly:
		return true
	default:
		return false
	}
}

type RelativeTimeInterval struct {
	CustomData *CustomData `json:"customData,omitempty" validate:"omitempty"`
	Start      int         `json:"start" validate:"required"`
	Duration   *int        `json:"duration,omitempty" validate:"omitempty"`
}

func NewRelativeTimeInterval(start int) RelativeTimeInterval {
	return RelativeTimeInterval{Start: start}
}

type RequestStartStopStatusType string

const (
	RequestStartStopStatusTypeAccepted RequestStartStopStatusType = "Accepted"
	RequestStartStopStatusTypeRejected RequestStartStopStatusType = "Rejected"
)

func isValidRequestStartStopStatusType(fl validator.FieldLevel) bool {
	requestStartStopStatus := RequestStartStopStatusType(fl.Field().String())
	switch requestStartStopStatus {
	case RequestStartStopStatusTypeAccepted, RequestStartStopStatusTypeRejected:
		return true
	default:
		return false
	}
}

type SalesTariff struct {
	CustomData             *CustomData        `json:"customData,omitempty" validate:"omitempty"`
	ID                     int                `json:"id" validate:"required"`
	SalesTariffDescription string             `json:"salesTariffDescription,omitempty" validate:"omitempty,max=32"`
	NumEPriceLevels        *int               `json:"numEPriceLevels,omitempty" validate:"omitempty"`
	SalesTariffEntry       []SalesTariffEntry `json:"salesTariffEntry" validate:"required,min=1,max=1024,dive"`
}

func NewSalesTariff(id int, salesTariffEntry []SalesTariffEntry) *SalesTariff {
	return &SalesTariff{ID: id, SalesTariffEntry: salesTariffEntry}
}

type SalesTariffEntry struct {
	CustomData           *CustomData          `json:"customData,omitempty" validate:"omitempty"`
	RelativeTimeInterval RelativeTimeInterval `json:"relativeTimeInterval" validate:"required"`
	EPriceLevel          *int                 `json:"ePriceLevel,omitempty" validate:"omitempty,gte=0"`
	ConsumptionCost      []ConsumptionCost    `json:"consumptionCost,omitempty" validate:"omitempty,min=1,max=3,dive"`
}

func NewSalesTariffEntry(relativeTimeInterval RelativeTimeInterval) SalesTariffEntry {
	return SalesTariffEntry{RelativeTimeInterval: relativeTimeInterval}
}

type SampledValue struct {
	CustomData       *CustomData        `json:"customData,omitempty" validate:"omitempty"`
	Value            float64            `json:"value" validate:"required"`
	Context          ReadingContextType `json:"context,omitempty" validate:"omitempty,readingContextType201"`
	Measurand        MeasurandType      `json:"measurand,omitempty" validate:"omitempty,measurandType201"`
	Phase            PhaseType          `json:"phase,omitempty" validate:"omitempty,phaseType201"`
	Location         LocationType       `json:"location,omitempty" validate:"omitempty,locationType201"`
	SignedMeterValue *SignedMeterValue  `json:"signedMeterValue,omitempty" validate:"omitempty"`
	UnitOfMeasure    *UnitOfMeasure     `json:"unitOfMeasure,omitempty" validate:"omitempty"`
}

func NewSampledValue(value float64) SampledValue {
	return SampledValue{Value: value}
}

type SignedMeterValue struct {
	CustomData      *CustomData `json:"customData,omitempty" validate:"omitempty"`
	SignedMeterData string      `json:"signedMeterData" validate:"required,max=2500"`
	SigningMethod   string      `json:"signingMethod" validate:"required,max=50"`
	EncodingMethod  string      `json:"encodingMethod" validate:"required,max=50"`
	PublicKey       string      `json:"publicKey" validate:"required,max=2500"`
}

func NewSignedMeterValue(signedMeterData string, signingMethod string, encodingMethod string, publicKey string) *SignedMeterValue {
	return &SignedMeterValue{SignedMeterData: signedMeterData, SigningMethod: signingMethod, EncodingMethod: encodingMethod, PublicKey: publicKey}
}

type StatusInfo struct {
	CustomData     *CustomData `json:"customData,omitempty" validate:"omitempty"`
	ReasonCode     string      `json:"reasonCode" validate:"required,max=20"`
	AdditionalInfo string      `json:"additionalInfo,omitempty" validate:"omitempty,max=512"`
}

func NewStatusInfo(reasonCode string) *StatusInfo {
	return &StatusInfo{ReasonCode: reasonCode}
}

type UnitOfMeasure struct {
	CustomData *CustomData `json:"customData,omitempty" validate:"omitempty"`
	Unit       string      `json:"unit,omitempty" validate:"omitempty,max=20"`
	Multiplier *int        `json:"multiplier,omitempty" validate:"omitempty"`
}

func NewUnitOfMeasure() *UnitOfMeasure {
	return &UnitOfMeasure{}
}

type Variable struct {
	CustomData *CustomData `json:"customData,omitempty" validate:"omitempty"`
	Name       string      `json:"name" validate:"required,max=50"`
	Instance   string      `json:"instance,omitempty" validate:"omitempty,max=50"`
}

func NewVariable(name string) *Variable {
	return &Variable{Name: name}
}

func init() {
	_ = Validate.RegisterValidation("attributeType201", isValidAttributeType)
	_ = Validate.RegisterValidation("authorizationStatusType201", isValidAuthorizationStatusType)
	_ = Validate.RegisterValidation("certificateSigningUseType201", isValidCertificateSigningUseType)
	_ = Validate.RegisterValidation("chargingLimitSourceType201", isValidChargingLimitSourceType)
	_ = Validate.RegisterValidation("chargingProfileKindType201", isValidChargingProfileKindType)
	_ = Validate.RegisterValidation("chargingProfilePurposeType201", isValidChargingProfilePurposeType)
	_ = Validate.RegisterValidation("chargingRateUnitType201", isValidChargingRateUnitType)
	_ = Validate.RegisterValidation("costKindType201", isValidCostKindType)
	_ = Validate.RegisterValidation("genericDeviceModelStatusType201", isValidGenericDeviceModelStatusType)
	_ = Validate.RegisterValidation("genericStatusType201", isValidGenericStatusType)
	_ = Validate.RegisterValidation("hashAlgorithmType201", isValidHashAlgorithmType)
	_ = Validate.RegisterValidation("idTokenType201", isValidIDTokenType)
	_ = Validate.RegisterValidation("locationType201", isValidLocationType)
	_ = Validate.RegisterValidation("measurandType201", isValidMeasurandType)
	_ = Validate.RegisterValidation("messageFormatType201", isValidMessageFormatType)
	_ = Validate.RegisterValidation("messagePriorityType201", isValidMessagePriorityType)
	_ = Validate.RegisterValidation("messageStateType201", isValidMessageStateType)
	_ = Validate.RegisterValidation("monitorType201", isValidMonitorType)
	_ = Validate.RegisterValidation("phaseType201", isValidPhaseType)
	_ = Validate.RegisterValidation("readingContextType201", isValidReadingContextType)
	_ = Validate.RegisterValidation("recurrencyKindType201", isValidRecurrencyKindType)
	_ = Validate.RegisterValidation("requestStartStopStatusType201", isValidRequestStartStopStatusType)
}
