// Code generated by internal/codegen. DO NOT EDIT.

package provisioning

import (
	"reflect"

	"gopkg.in/go-playground/validator.v9"

	"github.com/enesismail/ocpp-go/ocpp2.0.1/types"
)

// -------------------- Boot Notification (CS -> CSMS) --------------------

const BootNotificationFeatureName = "BootNotification"

type BootReasonType string

type RegistrationStatusType string

const (
	BootReasonTypeApplicationReset BootReasonType         = "ApplicationReset"
	BootReasonTypeFirmwareUpdate   BootReasonType         = "FirmwareUpdate"
	BootReasonTypeLocalReset       BootReasonType         = "LocalReset"
	BootReasonTypePowerUp          BootReasonType         = "PowerUp"
	BootReasonTypeRemoteReset      BootReasonType         = "RemoteReset"
	BootReasonTypeScheduledReset   BootReasonType         = "ScheduledReset"
	BootReasonTypeTriggered        BootReasonType         = "Triggered"
	BootReasonTypeUnknown          BootReasonType         = "Unknown"
	BootReasonTypeWatchdog         BootReasonType         = "Watchdog"
	RegistrationStatusTypeAccepted RegistrationStatusType = "Accepted"
	RegistrationStatusTypePending  RegistrationStatusType = "Pending"
	RegistrationStatusTypeRejected RegistrationStatusType = "Rejected"
)

func isValidBootReasonType(fl validator.FieldLevel) bool {
	bootReason := BootReasonType(fl.Field().String())
	switch bootReason {
	case BootReasonTypeApplicationReset, BootReasonTypeFirmwareUpdate, BootReasonTypeLocalReset, BootReasonTypePowerUp, BootReasonTypeRemoteReset, BootReasonTypeScheduledReset, BootReasonTypeTriggered, BootReasonTypeUnknown, BootReasonTypeWatchdog:
		return true
	default:
		return false
	}
}

func isValidRegistrationStatusType(fl validator.FieldLevel) bool {
	registrationStatus := RegistrationStatusType(fl.Field().String())
	switch registrationStatus {
	case RegistrationStatusTypeAccepted, RegistrationStatusTypePending, RegistrationStatusTypeRejected:
		return true
	default:
		return false
	}
}

type ChargingStation struct {
	CustomData      *types.CustomData `json:"customData,omitempty" validate:"omitempty"`
	SerialNumber    string            `json:"serialNumber,omitempty" validate:"omitempty,max=25"`
	Model           string            `json:"model" validate:"required,max=20"`
	Modem           *Modem            `json:"modem,omitempty" validate:"omitempty"`
	VendorName      string            `json:"vendorName" validate:"required,max=50"`
	FirmwareVersion string            `json:"firmwareVersion,omitempty" validate:"omitempty,max=50"`
}

type Modem struct {
	CustomData *types.CustomData `json:"customData,omitempty" validate:"omitempty"`
	Iccid      string            `json:"iccid,omitempty" validate:"omitempty,max=20"`
	Imsi       string            `json:"imsi,omitempty" validate:"omitempty,max=20"`
}

type BootNotificationRequest struct {
	CustomData      *types.CustomData `json:"customData,omitempty" validate:"omitempty"`
	ChargingStation ChargingStation   `json:"chargingStation" validate:"required"`
	Reason          BootReasonType    `json:"reason" validate:"required,bootReasonType201"`
}

type BootNotificationResponse struct {
	CustomData  *types.CustomData      `json:"customData,omitempty" validate:"omitempty"`
	CurrentTime *types.DateTime        `json:"currentTime" validate:"required"`
	Interval    int                    `json:"interval" validate:"required,gte=0"`
	Status      RegistrationStatusType `json:"status" validate:"required,registrationStatusType201"`
	StatusInfo  *types.StatusInfo      `json:"statusInfo,omitempty" validate:"omitempty"`
}

type BootNotificationFeature struct{}

func (f BootNotificationFeature) GetFeatureName() string {
	return BootNotificationFeatureName
}

func (f BootNotificationFeature) GetRequestType() reflect.Type {
	return reflect.TypeOf(BootNotificationRequest{})
}

func (f BootNotificationFeature) GetResponseType() reflect.Type {
	return reflect.TypeOf(BootNotificationResponse{})
}

func (r BootNotificationRequest) GetFeatureName() string {
	return BootNotificationFeatureName
}

func (c BootNotificationResponse) GetFeatureName() string {
	return BootNotificationFeatureName
}

func NewChargingStation(model string, vendorName string) ChargingStation {
	return ChargingStation{Model: model, VendorName: vendorName}
}

func NewModem() *Modem {
	return &Modem{}
}

func NewBootNotificationRequest(chargingStation ChargingStation, reason BootReasonType) *BootNotificationRequest {
	return &BootNotificationRequest{ChargingStation: chargingStation, Reason: reason}
}

func NewBootNotificationResponse(currentTime *types.DateTime, interval int, status RegistrationStatusType) *BootNotificationResponse {
	return &BootNotificationResponse{CurrentTime: currentTime, Interval: interval, Status: status}
}

func init() {
	_ = types.Validate.RegisterValidation("bootReasonType201", isValidBootReasonType)
	_ = types.Validate.RegisterValidation("registrationStatusType201", isValidRegistrationStatusType)
}
