// Code generated by internal/codegen. DO NOT EDIT.

package availability

import (
	"reflect"

	"github.com/enesismail/ocpp-go/ocpp2.0.1/types"
)

// -------------------- Heartbeat (CS -> CSMS) --------------------

const HeartbeatFeatureName = "Heartbeat"

type HeartbeatRequest struct {
	CustomData *types.CustomData `json:"customData,omitempty" validate:"omitempty"`
}

type HeartbeatResponse struct {
	CustomData  *types.CustomData `json:"customData,omitempty" validate:"omitempty"`
	CurrentTime *types.DateTime   `json:"currentTime" validate:"required"`
}

type HeartbeatFeature struct{}

func (f HeartbeatFeature) GetFeatureName() string {
	return HeartbeatFeatureName
}

func (f HeartbeatFeature) GetRequestType() reflect.Type {
	return reflect.TypeOf(HeartbeatRequest{})
}

func (f HeartbeatFeature) GetResponseType() reflect.Type {
	return reflect.TypeOf(HeartbeatResponse{})
}

func (r HeartbeatRequest) GetFeatureName() string {
	return HeartbeatFeatureName
}

func (c HeartbeatResponse) GetFeatureName() string {
	return HeartbeatFeatureName
}

func NewHeartbeatRequest() *HeartbeatRequest {
	return &HeartbeatRequest{}
}

func NewHeartbeatResponse(currentTime *types.DateTime) *HeartbeatResponse {
	return &HeartbeatResponse{CurrentTime: currentTime}
}
