// Code generated by internal/codegen. DO NOT EDIT.

package transactions

import (
	"reflect"

	"gopkg.in/go-playground/validator.v9"

	"github.com/enesismail/ocpp-go/ocpp2.0.1/types"
)

// -------------------- Transaction Event (CS -> CSMS) --------------------

const TransactionEventFeatureName = "TransactionEvent"

type ChargingStateType string

type ReasonType string

type TransactionEventType string

type TriggerReasonType string

const (
	ChargingStateTypeCharging             ChargingStateType    = "Charging"
	ChargingStateTypeEVConnected          ChargingStateType    = "EVConnected"
	ChargingStateTypeSuspendedEV          ChargingStateType    = "SuspendedEV"
	ChargingStateTypeSuspendedEVSE        ChargingStateType    = "SuspendedEVSE"
	ChargingStateTypeIdle                 ChargingStateType    = "Idle"
	ReasonTypeDeAuthorized                ReasonType           = "DeAuthorized"
	ReasonTypeEmergencyStop               ReasonType           = "EmergencyStop"
	ReasonTypeEnergyLimitReached          ReasonType           = "EnergyLimitReached"
	ReasonTypeEVDisconnected              ReasonType           = "EVDisconnected"
	ReasonTypeGroundFault                 ReasonType           = "GroundFault"
	ReasonTypeImmediateReset              ReasonType           = "ImmediateReset"
	ReasonTypeLocal                       ReasonType           = "Local"
	ReasonTypeLocalOutOfCredit            ReasonType           = "LocalOutOfCredit"
	ReasonTypeMasterPass                  ReasonType           = "MasterPass"
	ReasonTypeOther                       ReasonType           = "Other"
	ReasonTypeOvercurrentFault            ReasonType           = "OvercurrentFault"
	ReasonTypePowerLoss                   ReasonType           = "PowerLoss"
	ReasonTypePowerQuality                ReasonType           = "PowerQuality"
	ReasonTypeReboot                      ReasonType           = "Reboot"
	ReasonTypeRemote                      ReasonType           = "Remote"
	ReasonTypeSOCLimitReached             ReasonType           = "SOCLimitReached"
	ReasonTypeStoppedByEV                 ReasonType           = "StoppedByEV"
	ReasonTypeTimeLimitReached            ReasonType           = "TimeLimitReached"
	ReasonTypeTimeout                     ReasonType           = "Timeout"
	TransactionEventTypeEnded             TransactionEventType = "Ended"
	TransactionEventTypeStarted           TransactionEventType = "Started"
	TransactionEventTypeUpdated           TransactionEventType = "Updated"
	TriggerReasonTypeAuthorized           TriggerReasonType    = "Authorized"
	TriggerReasonTypeCablePluggedIn       TriggerReasonType    = "CablePluggedIn"
	TriggerReasonTypeChargingRateChanged  TriggerReasonType    = "ChargingRateChanged"
	TriggerReasonTypeChargingStateChanged TriggerReasonType    = "ChargingStateChanged"
	TriggerReasonTypeDeauthorized         TriggerReasonType    = "Deauthorized"
	TriggerReasonTypeEnergyLimitReached   TriggerReasonType    = "EnergyLimitReached"
	TriggerReasonTypeEVCommunicationLost  TriggerReasonType    = "EVCommunicationLost"
	TriggerReasonTypeEVConnectTimeout     TriggerReasonType    = "EVConnectTimeout"
	TriggerReasonTypeMeterValueClock      TriggerReasonType    = "MeterValueClock"
	TriggerReasonTypeMeterValuePeriodic   TriggerReasonType    = "MeterValuePeriodic"
	TriggerReasonTypeTimeLimitReached     TriggerReasonType    = "TimeLimitReached"
	TriggerReasonTypeTrigger              TriggerReasonType    = "Trigger"
	TriggerReasonTypeUnlockCommand        TriggerReasonType    = "UnlockCommand"
	TriggerReasonTypeStopAuthorized       TriggerReasonType    = "StopAuthorized"
	TriggerReasonTypeEVDeparted           TriggerReasonType    = "EVDeparted"
	TriggerReasonTypeEVDetected           TriggerReasonType    = "EVDetected"
	TriggerReasonTypeRemoteStop           TriggerReasonType    = "RemoteStop"
	TriggerReasonTypeRemoteStart          TriggerReasonType    = "RemoteStart"
	TriggerReasonTypeAbnormalCondition    TriggerReasonType    = "AbnormalCondition"
	TriggerReasonTypeSignedDataReceived   TriggerReasonType    = "SignedDataReceived"
	TriggerReasonTypeResetCommand         TriggerReasonType    = "ResetCommand"
)

func isValidChargingStateType(fl validator.FieldLevel) bool {
	chargingState := ChargingStateType(fl.Field().String())
	switch chargingState {
	case ChargingStateTypeCharging, ChargingStateTypeEVConnected, ChargingStateTypeSuspendedEV, ChargingStateTypeSuspendedEVSE, ChargingStateTypeIdle:
		return true
	default:
		return false
	}
}

func isValidReasonType(fl validator.FieldLevel) bool {
	reason := ReasonType(fl.Field().String())
	switch reason {
	case ReasonTypeDeAuthorized, ReasonTypeEmergencyStop, ReasonTypeEnergyLimitReached, ReasonTypeEVDisconnected, ReasonTypeGroundFault, ReasonTypeImmediateReset, ReasonTypeLocal, ReasonTypeLocalOutOfCredit, ReasonTypeMasterPass, ReasonTypeOther, ReasonTypeOvercurrentFault, ReasonTypePowerLoss, ReasonTypePowerQuality, ReasonTypeReboot, ReasonTypeRemote, ReasonTypeSOCLimitReached, ReasonTypeStoppedByEV, ReasonTypeTimeLimitReached, ReasonTypeTimeout:
		return true
	default:
		return false
	}
}

func isValidTransactionEventType(fl validator.FieldLevel) bool {
	transactionEvent := TransactionEventType(fl.Field().String())
	switch transactionEvent {
	case TransactionEventTypeEnded, TransactionEventTypeStarted, TransactionEventTypeUpdated:
		return true
	default:
		return false
	}
}

func isValidTriggerReasonType(fl validator.FieldLevel) bool {
	triggerReason := TriggerReasonType(fl.Field().String())
	switch triggerReason {
	case TriggerReasonTypeAuthorized, TriggerReasonTypeCablePluggedIn, TriggerReasonTypeChargingRateChanged, TriggerReasonTypeChargingStateChanged, TriggerReasonTypeDeauthorized, TriggerReasonTypeEnergyLimitReached, TriggerReasonTypeEVCommunicationLost, TriggerReasonTypeEVConnectTimeout, TriggerReasonTypeMeterValueClock, TriggerReasonTypeMeterValuePeriodic, TriggerReasonTypeTimeLimitReached, TriggerReasonTypeTrigger, TriggerReasonTypeUnlockCommand, TriggerReasonTypeStopAuthorized, TriggerReasonTypeEVDeparted, TriggerReasonTypeEVDetected, TriggerReasonTypeRemoteStop, TriggerReasonTypeRemoteStart, TriggerReasonTypeAbnormalCondition, TriggerReasonTypeSignedDataReceived, TriggerReasonTypeResetCommand:
		return true
	default:
		return false
	}
}

type Transaction struct {
	CustomData        *types.CustomData `json:"customData,omitempty" validate:"omitempty"`
	TransactionID     string            `json:"transactionId" validate:"required,max=36"`
	ChargingState     ChargingStateType `json:"chargingState,omitempty" validate:"omitempty,chargingStateType201"`
	TimeSpentCharging *int              `json:"timeSpentCharging,omitempty" validate:"omitempty"`
	StoppedReason     ReasonType        `json:"stoppedReason,omitempty" validate:"omitempty,reasonType201"`
	RemoteStartID     *int              `json:"remoteStartId,omitempty" validate:"omitempty"`
}

type TransactionEventRequest struct {
	CustomData         *types.CustomData    `json:"customData,omitempty" validate:"omitempty"`
	EventType          TransactionEventType `json:"eventType" validate:"required,transactionEventType201"`
	MeterValue         []types.MeterValue   `json:"meterValue,omitempty" validate:"omitempty,min=1,dive"`
	Timestamp          *types.DateTime      `json:"timestamp" validate:"required"`
	TriggerReason      TriggerReasonType    `json:"triggerReason" validate:"required,triggerReasonType201"`
	SeqNo              int                  `json:"seqNo" validate:"required"`
	Offline            *bool                `json:"offline,omitempty" validate:"omitempty"`
	NumberOfPhasesUsed *int                 `json:"numberOfPhasesUsed,omitempty" validate:"omitempty"`
	CableMaxCurrent    *int                 `json:"cableMaxCurrent,omitempty" validate:"omitempty"`
	ReservationID      *int                 `json:"reservationId,omitempty" validate:"omitempty"`
	TransactionInfo    Transaction          `json:"transactionInfo" validate:"required"`
	EVSE               *types.EVSE          `json:"evse,omitempty" validate:"omitempty"`
	IDToken            *types.IDToken       `json:"idToken,omitempty" validate:"omitempty"`
}

type TransactionEventResponse struct {
	CustomData             *types.CustomData     `json:"customData,omitempty" validate:"omitempty"`
	TotalCost              *float64              `json:"totalCost,omitempty" validate:"omitempty"`
	ChargingPriority       *int                  `json:"chargingPriority,omitempty" validate:"omitempty"`
	IDTokenInfo            *types.IDTokenInfo    `json:"idTokenInfo,omitempty" validate:"omitempty"`
	UpdatedPersonalMessage *types.MessageContent `json:"updatedPersonalMessage,omitempty" validate:"omitempty"`
}

type TransactionEventFeature struct{}

func (f TransactionEventFeature) GetFeatureName() string {
	return TransactionEventFeatureName
}

func (f TransactionEventFeature) GetRequestType() reflect.Type {
	return reflect.TypeOf(TransactionEventRequest{})
}

func (f TransactionEventFeature) GetResponseType() reflect.Type {
	return reflect.TypeOf(TransactionEventResponse{})
}

func (r TransactionEventRequest) GetFeatureName() string {
	return TransactionEventFeatureName
}

func (c TransactionEventResponse) GetFeatureName() string {
	return TransactionEventFeatureName
}

func NewTransaction(transactionID string) Transaction {
	return Transaction{TransactionID: transactionID}
}

func NewTransactionEventRequest(eventType TransactionEventType, timestamp *types.DateTime, triggerReason TriggerReasonType, seqNo int, transactionInfo Transaction) *TransactionEventRequest {
	return &TransactionEventRequest{EventType: eventType, Timestamp: timestamp, TriggerReason: triggerReason, SeqNo: seqNo, TransactionInfo: transactionInfo}
}

func NewTransactionEventResponse() *TransactionEventResponse {
	return &TransactionEventResponse{}
}

func init() {
	_ = types.Validate.RegisterValidation("chargingStateType201", isValidChargingStateType)
	_ = types.Validate.RegisterValidation("reasonType201", isValidReasonType)
	_ = types.Validate.RegisterValidation("transactionEventType201", isValidTransactionEventType)
	_ = types.Validate.RegisterValidation("triggerReasonType201", isValidTriggerReasonType)
}
